
defaults: &default
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
